Update nostr.py
Fix: Update add_relays() to add_relay() in nostr.py
Description
This PR fixes an issue , the method add_relays() was renamed to add_relay() and now accepts a single string instead of a list.

Error Message

AttributeError: 'Client' object has no attribute 'add_relays'. Did you mean: 'add_relay'?
After changing the code to use add_relay(), another error occurred:


The error occurred because the updated add_relay() method expects a string but was passed a list. This was due to the previous usage of add_relays() which accepted a list of URLs.


await client.add_relays(["ws://localhost:7777"])
To:
await client.add_relay("ws://localhost:7777")